### ISSUE TITLE
Add globalnet detection to framework using dynclient

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/shipyard#199] opened 2020-06-03 07:57 UTC
Submariner E2E tests detect the globalnet configuration dynamically [1] on init. Lighthouse does not do such detection and it would benefit from that to perform globalnet detection.

So we propose moving this detection (via dynclient) to the framework itself, then all framework usages can detect the globanet flag in the context.

[1] https://github.com/submariner-io/submariner/blob/master/test/e2e/framework/framework.go#L46

**Comment by vthapar** [comment] 2020-06-03 07:58
Would be good to detect at init and add a flag to context itself.

**Comment by tpantelis** [comment] 2020-06-26 03:09
This is a duplicate of https://github.com/submariner-io/shipyard/issues/72.

**Closed by tpantelis** 2020-06-26 03:09 UTC
Labels: go code, testing
